name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Clone Repo
      uses: actions/checkout@v1
    
    - name: Setup Visual Studio Command Prompt
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Build
      run: |
        msbuild /restore /t:Build,Pack src/WinUIEx/WinUIEx.csproj /p:Configuration=Release
        
    - name: Test
      run: |
        msbuild /restore /t:Build src\TestTools\WinUIUnitTests\WinUIUnitTests.csproj /p:Platform=x64 /p:Configuration=Release
        vstest.console.exe src\TestTools\WinUIUnitTests\bin\x64\Release\net6.0-windows10.0.19041.0\win10-x64\WinUIUnitTests.build.appxrecipe --logger:console;verbosity=normal /InIsolation
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: NuGet Packages
        path: artifacts\NuGet\Release
